from stabilizer_if import *

s=stabilizerClass("ms_control")
s.stream_kill=1
s.rewrite_conf=0
s.app_mode='CtrlRef'
s.telemetry_period=10
s.gain_afe0='G2'
s.gain_afe1='G1'
s.lut_config0_amplitude=0.5
s.lut_config0_phase_offset_deg=0
s.lut_config1_amplitude=1.0
s.lut_config1_phase_offset_deg=110
s.ctrl_offset=6.145
s.sig_ctrl_signal='Square'
s.sig_ctrl_frequency=14.671912560096153
s.sig_ctrl_amplitude=0.005
s.sig_ctrl_offset=0
s.sig_ctrl_stream_trigger='PeakMin'
s.stream_batch_request=4000
s.streams=['ErrMod', 'ErrDemod', 'CtrlDac', 'CtrlSig']
iir_ctrl=s.add_iir("iir_ctrl", s.sampling_freq/s.batch_size)
s.iir_ctrl.Kp=-0.1
s.iir_ctrl.Ki=-100
s.iir_ctrl.Kd=-5e-05
iir_ctrl.ba=s.iir_ctrl.compute_coeff()
#s.iir_ctrl.ba=[0,0,0,0,0]
s.iir_ctrl.y_offset=0
s.iir_ctrl.y_min=-2
s.iir_ctrl.y_max=2
plot=s.add_plot()
s.stream_decimation=1
s.plot.plots=['ErrMod', 'ErrDemod', 'CtrlDac', 'CtrlSig']
s.plot.xlim='auto'
#s.plot.xlim=(-1,1)
s.plot.ylim='auto'
#s.plot.ylim=[(-1,1),(-1,1),(-1,1)]
s.plot.xtype='time_us'
s.plot.tolerance=0.2
s.plot.refresh_ylim=1
